export const products = [
  {
    id: 1,
    name: "Apple iPhone 15 Pro Max 256GB хар",
    description:
      "Apple iPhone 15 Pro Max нь ухаалаг гар утасны шинэ технологийг танд хүргэж байна. A17 Pro процессор, Pro Grade камер систем, титан материалтай загвар.",
    originalPrice: 5999000,
    discountPrice: 5599000,
    discountPercent: 7,
    image: "/modern-smartphone.png",
    category: "Гар утас",
    store: "IT Store",
    originalUrl: "https://itstore.mn",
  },
  {
    id: 2,
    name: "Samsung Galaxy S24 Ultra 512GB ногоон",
    description:
      "Samsung Galaxy S24 Ultra нь AI технологи, 200MP камер, S Pen бичгийн хэрэгсэл бүхий хамгийн сүүлийн үеийн ухаалаг гар утас юм.",
    originalPrice: 5499000,
    discountPrice: 4899000,
    discountPercent: 11,
    image: "/samsung-smartphone.png",
    category: "Гар утас",
    store: "E-Monos",
    originalUrl: "https://emonos.mn",
  },
  {
    id: 3,
    name: "Apple MacBook Pro 14-inch M3 Pro 1TB",
    description: "Apple M3 Pro процессор, 14-inch Liquid Retina XDR дэлгэц, 18GB RAM, 1TB SSD хадгалалттай Mac.",
    originalPrice: 8999000,
    discountPrice: 8499000,
    discountPercent: 6,
    image: "/macbook-pro-on-desk.png",
    category: "Компьютер",
    store: "IT Store",
    originalUrl: "https://itstore.mn",
  },
  {
    id: 4,
    name: "Sony WH-1000XM5 чихэвч хар",
    description:
      "Sony WH-1000XM5 нь хамгийн сайн дуу чимээг бууруулах чадвартай, 30 цагийн батарейны ажиллагаатай, өндөр чанарын Hi-Res Audio дууны системтэй.",
    originalPrice: 1099000,
    discountPrice: 899000,
    discountPercent: 18,
    image: "/diverse-people-listening-headphones.png",
    category: "Аудио",
    store: "Shoppy",
    originalUrl: "https://shoppy.mn",
  },
  {
    id: 5,
    name: "Nike Air Force 1 '07 пүүз цагаан",
    description:
      "Өдөр тутмын хувцаслалтад тохирсон Nike Air Force 1 '07 пүүз нь тав тухтай, удаан эдэлгээтэй загвар юм.",
    originalPrice: 399000,
    discountPrice: 299000,
    discountPercent: 25,
    image: "/diverse-sneaker-collection.png",
    category: "Хувцас",
    store: "Goyol",
    originalUrl: "https://goyol.mn",
  },
  {
    id: 6,
    name: "DJI Air 3 Fly More Combo дрон",
    description:
      "DJI Air 3 нь 4K 60fps видео бичлэг хийх чадвартай, 46 минутын нислэгийн хугацаатай, автомат саадыг илрүүлэх системтэй.",
    originalPrice: 3499000,
    discountPrice: 2999000,
    discountPercent: 14,
    image: "/aerial-view-city.png",
    category: "Камер",
    store: "E-Monos",
    originalUrl: "https://emonos.mn",
  },
  {
    id: 7,
    name: "Samsung 65-inch QN90C Neo QLED 4K TV",
    description:
      "Samsung Neo QLED телевиз нь Quantum Matrix технологи, Neo Quantum Processor 4K, Dolby Atmos дуу, Gaming Hub зэрэг олон шинэлэг функцтай.",
    originalPrice: 6499000,
    discountPrice: 5499000,
    discountPercent: 15,
    image: "/4k-tv-display.png",
    category: "Электрон",
    store: "IT Store",
    originalUrl: "https://itstore.mn",
  },
  {
    id: 8,
    name: "Adidas Ultraboost Light гүйлтийн пүүз",
    description:
      "Adidas Ultraboost Light нь гүйлтийн үед хөнгөн, тав тухтай байдлыг хангахаар бүтээгдсэн бөгөөд Linear Energy Push системтэй.",
    originalPrice: 499000,
    discountPrice: 349000,
    discountPercent: 30,
    image: "/running-shoes-on-track.png",
    category: "Хувцас",
    store: "Goyol",
    originalUrl: "https://goyol.mn",
  },
  {
    id: 9,
    name: "Apple iPad Pro 12.9-inch M2 256GB WIFI",
    description:
      "Apple iPad Pro нь M2 чип, 12.9-inch Liquid Retina XDR дэлгэц, ProMotion технологи, Center Stage нүүрний камертай.",
    originalPrice: 3699000,
    discountPrice: 3299000,
    discountPercent: 11,
    image: "/ipad-pro.png",
    category: "Таблет",
    store: "E-Monos",
    originalUrl: "https://emonos.mn",
  },
  {
    id: 10,
    name: "Sony PlayStation 5 Pro Console",
    description:
      "PlayStation 5 Pro нь хамгийн сүүлийн үеийн тоглоомын консол бөгөөд Ray Tracing технологи, Ultra HD тоглох боломж, PS VR2 дэмжлэгтэй.",
    originalPrice: 2999000,
    discountPrice: 2799000,
    discountPercent: 7,
    image: "/playstation-5-console.png",
    category: "Тоглоом",
    store: "Shoppy",
    originalUrl: "https://shoppy.mn",
  },
  {
    id: 11,
    name: "Dyson V15 Detect Absolute шорданз",
    description:
      "Dyson V15 Detect нь хөнгөн, хүчирхэг, лазер технологитой бөгөөд тоос шороог хамгийн сайн илрүүлж цэвэрлэнэ.",
    originalPrice: 2499000,
    discountPrice: 1999000,
    discountPercent: 20,
    image: "/classic-vacuum-cleaner.png",
    category: "Гэр ахуй",
    store: "E-Monos",
    originalUrl: "https://emonos.mn",
  },
  {
    id: 12,
    name: "Canon EOS R6 Mark II Body",
    description:
      "Canon EOS R6 Mark II нь 24.2MP сенсор, 40fps шууд зураг авах хурд, 6K RAW видео бичлэг хийх боломжтой мэргэжлийн камер.",
    originalPrice: 5899000,
    discountPrice: 5399000,
    discountPercent: 8,
    image: "/digital-camera.png",
    category: "Камер",
    store: "IT Store",
    originalUrl: "https://itstore.mn",
  },
]

export const stores = [
  {
    id: 1,
    name: "IT Store",
    description: "Электрон бараа, гар утас, компьютер, таблет зэрэг",
    logo: "/tech-store-logo.png",
    productCount: 352,
    averageDiscount: 10,
    websiteUrl: "https://itstore.mn",
  },
  {
    id: 2,
    name: "E-Monos",
    description: "Монголын хамгийн том онлайн их дэлгүүр",
    logo: "/online-marketplace-logo.png",
    productCount: 1240,
    averageDiscount: 15,
    websiteUrl: "https://emonos.mn",
  },
  {
    id: 3,
    name: "Shoppy",
    description: "Гэр ахуйн бараа, цахилгаан хэрэгсэл",
    logo: "/appliance-store-logo.png",
    productCount: 528,
    averageDiscount: 12,
    websiteUrl: "https://shoppy.mn",
  },
  {
    id: 4,
    name: "Goyol",
    description: "Хувцас, гутал, спорт хэрэгсэл",
    logo: "/placeholder.svg?height=200&width=400&query=fashion%20store%20logo",
    productCount: 845,
    averageDiscount: 25,
    websiteUrl: "https://goyol.mn",
  },
  {
    id: 5,
    name: "Tech Mall",
    description: "Компьютер, принтер, сүлжээний тоног төхөөрөмж",
    logo: "/placeholder.svg?height=200&width=400&query=computer%20store%20logo",
    productCount: 342,
    averageDiscount: 8,
    websiteUrl: "https://techmall.mn",
  },
  {
    id: 6,
    name: "Nomin Electronics",
    description: "Телевиз, аудио систем, гэр ахуйн цахилгаан хэрэгсэл",
    logo: "/placeholder.svg?height=200&width=400&query=electronics%20store%20logo",
    productCount: 423,
    averageDiscount: 11,
    websiteUrl: "https://nominelectronics.mn",
  },
]
